### ISSUE TITLE
"Mit Gesundheitskarte anmelden" verschwindet nicht, nachdem man sich mit der Gesundheitskarte angemeldet hat

### ISSUE THREAD

**Issue by cheindel** [gematik/E-Rezept-App-iOS#1]
Die Kachel "Mit Gesundheitskarte anmelden" im Reiter "Rezepte" verschwindet nicht, nachdem man sich mit der Gesundheitskarte angemeldet hat.

Das Problem tritt auf in Version 1.1.2, war aber auch in früheren Versionen bereits zu beobachten.

**Comment by mabasger** [comment]
Hi, frohes neues, und vielen Dank für den Hinweis!

Den Bug sind wir gerade am Fixen, zusammen mit einem Refactoring des Mainscreens. Sollte in einem der nächsten Releases endlich rauskommen.

Aber vielen Dank für das Interesse an der E-Rezept App, und immer gerne her mit den Fehlermeldungen :-)
