### ISSUE TITLE
Ein von der Praxis storniertes / gelöschtes Rezept taucht in der App immer noch als "Einlösbar" auf

### ISSUE THREAD

**Issue by cheindel** [gematik/E-Rezept-App-iOS#2]
Auch 18 Tage nach der Löschung / Stornierung des Rezepts und nach Neuanmeldung in der App wird das Rezept noch als "Einlösbar" angezeigt.

In der Apotheke wird es korrekterweise nicht mehr akzeptiert, wenn man versucht es einzulösen. Scheint also ein Darstellungs- / Aktualisierungsproblem in der App zu sein.

**Comment by luiseque** [comment]
Vielen Dank. Uns ist der Fehler bekannt. Die Information, dass ein Rezept gelöscht ist, wird erst seit kurzem an die Telematik Infrastruktur weitergeleitet. Wir implementieren daher im Moment den gelöscht - Status. Bitte entschuldigen Sie die Unannehmlichkeiten, der Fehler sollte in Kürze nicht mehr auftreten!
